Repository 42wim/matterircd, pull requests merged in 2021-02, with the labels that each got.

#398 Fixed buffer flushing
  mm-go-irckit/user.go
Labels: bug

#393 Show scrollback in same channel/query window
  mm-go-irckit/service.go
  mm-go-irckit/userbridge.go
Labels: breaking, enhancement

#402 Use conversation API for DM (slack)
  bridge/slack/slack.go
Labels: bug

#401 Update vendor - latest slack-go
  go.mod
  go.sum
  vendor/github.com/slack-go/slack/.golangci.yml
  vendor/github.com/slack-go/slack/.gometalinter.json
  vendor/github.com/slack-go/slack/.travis.yml
  vendor/github.com/slack-go/slack/CHANGELOG.md
  vendor/github.com/slack-go/slack/README.md
  vendor/github.com/slack-go/slack/apps.go
  vendor/github.com/slack-go/slack/attachments.go
  vendor/github.com/slack-go/slack/block.go
  vendor/github.com/slack-go/slack/block_action.go
  vendor/github.com/slack-go/slack/block_conv.go
  vendor/github.com/slack-go/slack/block_element.go
  vendor/github.com/slack-go/slack/block_input.go
  vendor/github.com/slack-go/slack/block_object.go
  vendor/github.com/slack-go/slack/channels.go
  vendor/github.com/slack-go/slack/chat.go
  vendor/github.com/slack-go/slack/conversation.go
  vendor/github.com/slack-go/slack/dialog.go
  vendor/github.com/slack-go/slack/files.go
  vendor/github.com/slack-go/slack/go.sum
  vendor/github.com/slack-go/slack/groups.go
  vendor/github.com/slack-go/slack/im.go
  vendor/github.com/slack-go/slack/interactions.go
  vendor/github.com/slack-go/slack/internal/backoff/backoff.go
  vendor/github.com/slack-go/slack/internal/errorsx/errorsx.go
  vendor/github.com/slack-go/slack/internal/misc/misc.go
  vendor/github.com/slack-go/slack/logger.go
  vendor/github.com/slack-go/slack/logo.png
  vendor/github.com/slack-go/slack/messages.go
  vendor/github.com/slack-go/slack/misc.go
  vendor/github.com/slack-go/slack/reminders.go
  vendor/github.com/slack-go/slack/security.go
  vendor/github.com/slack-go/slack/slack.go
  vendor/github.com/slack-go/slack/slash.go
  vendor/github.com/slack-go/slack/socket_mode.go
  vendor/github.com/slack-go/slack/users.go
  vendor/github.com/slack-go/slack/websocket_managed_conn.go
  vendor/modules.txt
Labels: enhancement

#403 Fix regression, increase user pag to 1000 (slack)
  vendor/github.com/slack-go/slack/users.go
Labels: bug
